name: Build and upload to PyPI

# -----------------------------------------------------------------------------
# GLOBAL SETTINGS
# -----------------------------------------------------------------------------
env:
  # Drop both 3.6 and 3.7 wheels
  CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-* cp313-*"


# Build on every push (branches & tags), PR update, and manual dispatch
on:
  push:
    branches: ["**"]
    tags: ["v*"]
  pull_request:
  workflow_dispatch:

# -----------------------------------------------------------------------------
# 1. Build wheels (all platforms)
# -----------------------------------------------------------------------------
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # `windows-2019` retires 2025-06-30 – use supported images instead
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4          # ← upgrade
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.18.1     # ← latest stable

      - name: Upload wheels
        uses: actions/upload-artifact@v4    # ← upgrade
        with:
          name: wheels
          path: wheelhouse/*.whl
          retention-days: 7                 # optional, defaults to 90

# -----------------------------------------------------------------------------
# 2. Build sdist (Linux only)
# -----------------------------------------------------------------------------
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build sdist
        run: pipx run build --sdist

      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
          retention-days: 7

# -----------------------------------------------------------------------------
# 3. Publish to PyPI (only when a tag that starts with `v` is pushed)
# -----------------------------------------------------------------------------
  upload_pypi:
    needs: [build_wheels, build_sdist]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4  # ← upgrade
        with:
          pattern: '*'
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.15
        with:
          user: ${{ secrets.PYPI_USER }}
          password: ${{ secrets.PYPI_PROD_PASSWORD }}
          verbose: true
          # For test releases, uncomment ↓
          # repository_url: https://test.pypi.org/legacy/
